name: Deploy from development

on: [push]

jobs:
 
  build_and_push_on_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 
        with:
            push: true
            tags: ${{ secrets.DOCKER_TAG }}

    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: build_and_push_on_dockerhub
    #     steps:
    #         - name: executing remote ssh commands to deploy
    #             uses: appleboy/ssh-action@master
    #             with:
    #             host: ${{ secrets.HOST }}
    #             username: ${{ secrets.USER }}
    #             key: ${{ secrets.SSH_KEY }}
    #             passphrase: ${{ secrets.PASSPHRASE }}
    #             script: |
    #                 sudo docker pull temacu/infra_actions
    #                 sudo docker stop $(sudo docker ps -a -q)
    #                 sudo docker run --rm -d -p 5000:5000 temacu/infra_actions

  # send_message:
  #     runs-on: ubuntu-latest
  #     needs: build_and_push_on_dockerhub  # !!!!
  #     steps:
  #         - name: send message
  #           uses: appleboy/telegram-action@master
  #           with:
  #             to: ${{ secrets.TELEGRAM_TO }}
  #             token: ${{ secrets.TELEGRAM_TOKEN }}
  #             message: |+
  #                 ${{ github.actor }}
  #                 pushed ${{ github.repository }}
  #                 << ${{ github.event.head_commit.message }} >>
  #                 + Deployed on dockerhub (${{ secrets.DOCKER_TAG }})!